### ISSUE TITLE
Removing 'StatusBar' from imports in 'PetsList.js' causes the app to crash

### ISSUE THREAD

**Issue by jsanchezperuga** [00frank/patitapp#5]
Error mesage in mobile
![image](https://user-images.githubusercontent.com/66560125/141706759-031b3028-55e2-4166-9bce-8638dc3da3aa.png)
Error message in VSC console
![image](https://user-images.githubusercontent.com/66560125/141707236-551e71e0-aa78-4fae-9ba7-0e9820f4adf1.png)

**Comment by jsanchezperuga** [comment]
Solution: restore the import and restart the app.
![image](https://user-images.githubusercontent.com/66560125/141706924-a9eab4f0-46c3-41ca-b517-52d95170929d.png)

**Comment by 00frank** [comment]
Se re-hicieron los cambios en un nuevo commit [`c5cba5b`](https://github.com/00frank/patitapp/commit/c5cba5b1c2d222c7485a6c09b4521c8a6f2a2286)
